# Generated by Django 5.2.4 on 2025-11-03 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0002_remove_profile_first_name_remove_profile_last_name_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
