# Generated by Django 5.2.4 on 2025-11-03 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0003_delete_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='first_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='first name'),
        ),
        migrations.AddField(
            model_name='user',
            name='last_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='last name'),
        ),
    ]
