# Generated by Django 5.2.4 on 2025-11-03 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0004_user_first_name_user_last_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='about_description',
            field=models.CharField(blank=True, default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='user',
            name='bank_account_number',
            field=models.CharField(blank=True, default='', max_length=34),
        ),
        migrations.AddField(
            model_name='user',
            name='bank_recipient',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='user',
            name='birthdate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='city',
            field=models.CharField(blank=True, choices=[('Alytus', 'Alytus'), ('Anykščiai', 'Anyksciai'), ('Akmenė', 'Akmene'), ('Biržai', 'Birzai'), ('Birštonas', 'Birstonas'), ('Druskininkai', 'Druskininkai'), ('Elektrėnai', 'Elektrenai'), ('Gargždai', 'Gargzdai'), ('Ignalina', 'Ignalina'), ('Jonava', 'Jonava'), ('Joniškis', 'Joniskis'), ('Jurbarkas', 'Jurbarkas'), ('Kaunas', 'Kaunas'), ('Kaišiadorys', 'Kaisiadorys'), ('Kalvarija', 'Kalvarija'), ('Kazlų Rūda', 'Kazlu Ruda'), ('Kėdainiai', 'Kedainiai'), ('Kelmė', 'Kelme'), ('Klaipėda', 'Klaipeda'), ('Krekenava', 'Krekenava'), ('Kretinga', 'Kretinga'), ('Kupiškis', 'Kupiskis'), ('Kuršėnai', 'Kursenai'), ('Lazdijai', 'Lazdijai'), ('Lentvaris', 'Lentvaris'), ('Marijampolė', 'Marijampole'), ('Mažeikiai', 'Mazeikiai'), ('Molėtai', 'Moletai'), ('Naujoji Akmenė', 'Naujoji Akmene'), ('Nemenčinė', 'Nemencine'), ('Neringa', 'Neringa'), ('Pabradė', 'Pabrade'), ('Pagėgiai', 'Pagegiai'), ('Pakruojis', 'Pakruojis'), ('Palanga', 'Palanga'), ('Pasvalys', 'Pasvalys'), ('Plungė', 'Plunge'), ('Prienai', 'Prienai'), ('Radviliškis', 'Radviliskis'), ('Raseiniai', 'Raseiniai'), ('Rietavas', 'Rietavas'), ('Rokiškis', 'Rokiskis'), ('Šakiai', 'Sakiai'), ('Šalčininkai', 'Salcininkai'), ('Šilalė', 'Silale'), ('Šilutė', 'Silute'), ('Širvintos', 'Sirvintos'), ('Skuodas', 'Skuodas'), ('Švenčionys', 'Svencionys'), ('Šiauliai', 'Siauliai'), ('Tauragė', 'Taurage'), ('Telšiai', 'Telsiai'), ('Trakai', 'Trakai'), ('Ukmergė', 'Ukmerge'), ('Utena', 'Utena'), ('Varėna', 'Varena'), ('Vievis', 'Vievis'), ('Vilkaviškis', 'Vilkaviskis'), ('Vilnius', 'Vilnius'), ('Visaginas', 'Visaginas'), ('Zarasai', 'Zarasai')], default='', max_length=50),
        ),
        migrations.AddField(
            model_name='user',
            name='gender',
            field=models.CharField(blank=True, choices=[('vyras', 'Vyras'), ('moteris', 'Moteris')], default='', max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='is_accepting_meetings',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='meeting_time_description',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='user',
            name='price_per_hour',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
