# Generated by Django 5.2.4 on 2025-11-12 19:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0006_user_interest1_user_interest2_user_interest3_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='price_per_hour',
        ),
        migrations.AddField(
            model_name='user',
            name='profit_per_hour',
            field=models.PositiveIntegerField(default=5, validators=[django.core.validators.MinValueValidator(5)]),
        ),
    ]
