# Generated by Django 5.2.4 on 2025-11-13 20:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0008_friendmeetingtime'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='meeting_time_description',
        ),
    ]
