# Generated by Django 5.2.4 on 2025-11-19 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0009_remove_user_meeting_time_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='about_description',
            field=models.TextField(blank=True, default=''),
        ),
    ]
