# Generated by Django 6.0 on 2025-12-04 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0010_alter_user_about_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friendmeetingtime',
            name='fri_day',
            field=models.BooleanField(default=True, verbose_name='Available Friday'),
        ),
        migrations.AlterField(
            model_name='friendmeetingtime',
            name='mon_day',
            field=models.BooleanField(default=True, verbose_name='Available Monday'),
        ),
        migrations.AlterField(
            model_name='friendmeetingtime',
            name='sat_day',
            field=models.BooleanField(default=True, verbose_name='Available Saturday'),
        ),
        migrations.AlterField(
            model_name='friendmeetingtime',
            name='sun_day',
            field=models.BooleanField(default=True, verbose_name='Available Sunday'),
        ),
        migrations.AlterField(
            model_name='friendmeetingtime',
            name='thu_day',
            field=models.BooleanField(default=True, verbose_name='Available Thursday'),
        ),
        migrations.AlterField(
            model_name='friendmeetingtime',
            name='tue_day',
            field=models.BooleanField(default=True, verbose_name='Available Tuesday'),
        ),
        migrations.AlterField(
            model_name='friendmeetingtime',
            name='wed_day',
            field=models.BooleanField(default=True, verbose_name='Available Wednesday'),
        ),
        migrations.AlterField(
            model_name='user',
            name='city',
            field=models.CharField(blank=True, choices=[('alytus', 'Alytus'), ('anyksciai', 'Anykščiai'), ('akmene', 'Akmenė'), ('birzai', 'Biržai'), ('birstonas', 'Birštonas'), ('druskininkai', 'Druskininkai'), ('elektrenai', 'Elektrėnai'), ('gargzdai', 'Gargždai'), ('ignalina', 'Ignalina'), ('jonava', 'Jonava'), ('joniskis', 'Joniškis'), ('jurbarkas', 'Jurbarkas'), ('kaunas', 'Kaunas'), ('kaisiadorys', 'Kaišiadorys'), ('kalvarija', 'Kalvarija'), ('kazlu_ruda', 'Kazlų Rūda'), ('kedainiai', 'Kėdainiai'), ('kelme', 'Kelmė'), ('klaipeda', 'Klaipėda'), ('krekenava', 'Krekenava'), ('kretinga', 'Kretinga'), ('kupiskis', 'Kupiškis'), ('kursenai', 'Kuršėnai'), ('lazdijai', 'Lazdijai'), ('lentvaris', 'Lentvaris'), ('marijampole', 'Marijampolė'), ('mazeikiai', 'Mažeikiai'), ('moletai', 'Molėtai'), ('naujoji_akmene', 'Naujoji Akmenė'), ('nemencine', 'Nemenčinė'), ('neringa', 'Neringa'), ('pabrade', 'Pabradė'), ('pagegiai', 'Pagėgiai'), ('pakruojis', 'Pakruojis'), ('palanga', 'Palanga'), ('pasvalys', 'Pasvalys'), ('plunge', 'Plungė'), ('prienai', 'Prienai'), ('radviliskis', 'Radviliškis'), ('raseiniai', 'Raseiniai'), ('rietavas', 'Rietavas'), ('rokiskis', 'Rokiškis'), ('sakiai', 'Šakiai'), ('salcininkai', 'Šalčininkai'), ('silale', 'Šilalė'), ('silute', 'Šilutė'), ('sirvintos', 'Širvintos'), ('skuodas', 'Skuodas'), ('svencionys', 'Švenčionys'), ('siauliai', 'Šiauliai'), ('taurage', 'Tauragė'), ('telsiai', 'Telšiai'), ('trakai', 'Trakai'), ('ukmerge', 'Ukmergė'), ('utena', 'Utena'), ('varena', 'Varėna'), ('vievis', 'Vievis'), ('vilkaviskis', 'Vilkaviškis'), ('vilnius', 'Vilnius'), ('visaginas', 'Visaginas'), ('zarasai', 'Zarasai')], default='', max_length=50),
        ),
    ]
