# Generated by Django 6.0 on 2025-12-09 21:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0016_alter_friendmeetingtime_fri_from_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='meeting',
            old_name='lon',
            new_name='lng',
        ),
    ]
