# Generated by Django 6.0 on 2026-01-15 19:41

import db.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0017_rename_lon_meeting_lng'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='confirmation_code',
            field=models.CharField(default=db.models.generate_confirmation_code, max_length=5),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='status',
            field=models.IntegerField(choices=[(1, 'Created'), (2, 'Confirmed'), (3, 'Completed'), (4, 'Failed'), (5, 'Declined'), (6, 'Expired')], default=1),
        ),
    ]
