# Generated by Django 6.0 on 2026-01-15 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0018_meeting_confirmation_code_alter_meeting_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='declined_reason',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
