# Generated by Django 6.0 on 2026-01-17 18:26

import db.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0019_meeting_declined_reason'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofilepicture',
            name='avatar',
            field=models.ImageField(upload_to=db.models.user_avatar_upload_path),
        ),
    ]
