# Generated by Django 6.0 on 2026-01-17 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0020_alter_userprofilepicture_avatar'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofilepicture',
            old_name='avatar',
            new_name='image',
        ),
        migrations.AddField(
            model_name='userprofilepicture',
            name='is_avatar',
            field=models.BooleanField(default=False),
        ),
    ]
