# Generated by Django 6.0 on 2026-01-20 18:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0021_rename_avatar_userprofilepicture_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payer_email', models.EmailField(max_length=254)),
                ('platform_fee', models.PositiveIntegerField()),
                ('reference_code', models.PositiveBigIntegerField(editable=False, unique=True)),
                ('has_paid', models.BooleanField(default=False)),
                ('is_grace_period', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='db.meeting')),
                ('payer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
