# Generated by Django 6.0 on 2026-01-20 18:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0022_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='meeting',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='db.meeting'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='reference_code',
            field=models.PositiveBigIntegerField(blank=True, editable=False, null=True, unique=True),
        ),
    ]
