# Generated by Django 6.0 on 2026-02-12 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0025_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='banned',
            field=models.IntegerField(blank=True, choices=[(1, 'Unpaid meeting'), (2, 'Bad behavior')], null=True),
        ),
    ]
