# Generated by Django 5.2.11 on 2026-04-24 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0027_alter_user_banned_useremaillog_meetingemaillog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='content',
            field=models.TextField(max_length=1000),
        ),
    ]
